### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by joncasdam** [pybee/pybee.github.io#102]
I think would be a good addition to have a language selector or, perhaps, a page with a link to browse to existing translations.

**Comment by glasnt** [comment]
Hi @joncasdam. This sounds like a great idea! The [lektor docs](https://www.getlektor.com/docs/content/alts/) don't detail how to do this, but [this gist](https://gist.github.com/skz169/e5801df6e894f39cb2de) might help if you wanted to implement a language selector in the website header

**Comment by joncasdam** [comment]
Grerat. I'm on it.

**Comment by joncasdam** [comment]
Fix added as part of https://github.com/pybee/pybee.github.io/pull/107, @glasnt

**Comment by joncasdam** [comment]
Done at #107
