### ISSUE TITLE
using/ios-app/ actually makes reference to Android instead of iOS

### ISSUE THREAD

**Issue by joncasdam** [pybee/pybee.github.io#105]
In the last paragraph it says:

> Once you've written your native iOS application, you can use Briefcase to package your Python code as an iOS application bundle. Briefcase takes the distutils setup.py definition for your Python project, and uses that metadata to generate a stub iOS Xcode project, and add your Python code and dependencies so that they will be found when you run your the **Android** project. The stub project is generated using the Python iOS template.

It should be iOS, right?

**Comment by freakboy3742** [comment]
Looks like an oversight, yes!

**Comment by joncasdam** [comment]
Closing for has already been merged at https://github.com/pybee/pybee.github.io/pull/106
