### ISSUE TITLE
Feed for news?

### ISSUE THREAD

**Issue by clokep** [pybee/pybee.github.io#116]
Thanks for an awesome project so far! I've been eagerly following along. I went to http://pybee.org/news/ and was hoping to follow project news easily, unfortunately there's no RSS/Atom feed.

It looks like there's a lektor plugin that could enable this: https://github.com/ajdavis/lektor-atom

**Comment by clokep** [comment]
Hmm...I now see a http://pybee.org/news@atom/buzz page, but that doesn't seem to actually have any data (404s).

**Comment by freakboy3742** [comment]
Apologies - something went wonky in the deployment process. This should be fixed now.

**Comment by clokep** [comment]
Sweet. Thanks! 👍 

If anyone in the future finds this, the correct URL is http://pybee.org/news/buzz/atom.xml
