### ISSUE TITLE
Debug auto deploy

### ISSUE THREAD

**Issue by willingc** [pybee/pybee.github.io#12]
@freakboy3742 @singingwolfboy 

`Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.`

Wondering if telling Travis to `deploy.skip_cleanup:true` would help???

**Comment by singingwolfboy** [comment]
No, I'm pretty sure that's unrelated. There _is_ a Git repo, so the artifacts are there, it's just that the URL is wrong. I think I have a fix in https://github.com/lektor/lektor/pull/240, but I'm not certain.

**Comment by freakboy3742** [comment]
Deployed using a forked version of Lector in 3e6964bcc. When lektor/lektor#240 is merged and a new version of Lektor is released, we can move back to a trunk version of Lektor. Leaving this ticket open until then.

**Comment by jambonrose** [comment]
Quick note: lektor/lektor#240 has been merged!

**Comment by goanpeca** [comment]
Can we close this issue @willingc ?

**Comment by willingc** [comment]
Sure @goanpeca
