### ISSUE TITLE
Fix links on Contributing page

### ISSUE THREAD

**Issue by phildini** [pybee/pybee.github.io#133]
If you look at https://pybee.org/contributing/how/ you'll notice the links in the "Code Contribution" section look a little weird.

There are other examples on that page for how to fix the links. 

https://github.com/pybee/pybee.github.io/blob/lektor/content/contributing/how/contents.lr#L56

**Comment by ne0zen** [comment]
FYI:
https://github.com/pybee/pybee.github.io/blob/master/content/contributing/how/contents.lr#L56

results in a 404 for me.

**Comment by phildini** [comment]
@ne0zen yep! You're right! Updated to use the right branch.

**Comment by ne0zen** [comment]
@phildini thanks!  I'm happy to take this on if desired.

**Comment by phildini** [comment]
@ne0zen If you look at the page, it's been fixed!
