### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by goanpeca** [pybee/pybee.github.io#155]
Hello!, this project is awesome and I would like to contribute in the near future. In the meantime I can start by translating to Spanish. (Also I really like Lektor :-p )

Greetings from Colombia.

**Comment by goanpeca** [comment]
@freakboy3742 do you prefer that this work is made in separate PRs, batches (per group of pages etc..) or as a massive single PR? I am guessing the former is better.

**Comment by freakboy3742** [comment]
Thanks for the kind words! 

As for the PR approach - whatever works well for your workflow is fine. As long as it's clear from our end when a translation is complete and ready for merge, we don't much mind whether it comes in 1 PR or 10.

**Comment by goanpeca** [comment]
I wrote a small selenium script to parse all the files and autogenerate the new translation files based on Google translate. With this in hand, I will just adjust the translations (plus this saves a lot of time)

Maybe we could use this approach for other translations?

**Comment by freakboy3742** [comment]
Sure - depends how good the initial translations are, I suppose...

**Comment by freakboy3742** [comment]
If it turns out that the translations are reliable enough straight out of Google Translate, it might be nice to set this up as an automated commit trigger. That way, every time new content is added to the website, it could be automatically translated to provide a first draft, either as a pull request with the automatically generated content, or raising an issue that flags that a new translation needs to be reviewed.

This would actually be a good candidate for a [Beefore](https://github.com/pybee/beefore) task...

**Comment by goanpeca** [comment]
>If it turns out that the translations are reliable enough straight out of Google Translate, it might be nice to set this up as an automated commit trigger. That way, every time new content is added to the website, it could be automatically translated to provide a first draft, either as a pull request with the automatically generated content, or raising an issue that flags that a new translation needs to be reviewed.

Sure thing :-), sounds, good. I need to polish a bit the script, I am almost there, If we used the translate api from google it would be probably much faster than the selenium approach, but only the initial batch thing takes a bit long...

On another point, is there a Translators team created on the org? it could be read access only for now, but is good to have some visibility on that side, so others feel encouraged to join in and help.

**Comment by freakboy3742** [comment]
There isn't currently a translators team; if you think that would help with organisation, I'm happy to set one up.

**Comment by freakboy3742** [comment]
A related activity - there's not much use *having* a team unless people know it exists; so we probably need some documentation for how to get started on translation, how to contribute, what you need to do to join the translation team, etc. Care to take a swing at drafting something?

**Comment by goanpeca** [comment]
>A related activity - there's not much use having a team unless people know it exists; so we probably need some documentation for how to get started on translation, how to contribute, what you need to do to join the translation team, etc. Care to take a swing at drafting something?

Sure thing

**Comment by pwaqo** [comment]
Hello, I'm from Spain and would like also to contribute translating this. What is the status of the Selenium script? @goanpeca

**Comment by goanpeca** [comment]
@pwaqo thanks for the help, this week I am pushing the PR with all the translations. You could help me a lot by proofreading :-)

**Comment by pwaqo** [comment]
:+1:  @goanpeca
