### ISSUE TITLE
Pipenv should be added to Setting up your environment guide.

### ISSUE THREAD

**Issue by RatanShreshtha** [pybee/pybee.github.io#224]
[Pipenv](https://github.com/kennethreitz/pipenv) — the officially recommended Python packaging tool from Python.org, free (as in freedom).
It automatically creates and manages a virtualenv for your projects, as well as adds/removes packages from your Pipfile as you install/uninstall packages.

And it is much easier to setup virtual environment with different python versions with Pipenv.

**Comment by freakboy3742** [comment]
I haven't had a chance to play around with pipenv; it's also a very new tool, and possibly prone to changes so I'm hesitant to recommend it at this time. This might change in the future if pipenv stabilises and gains really widespread usage.
