### ISSUE TITLE
The language menu shouldn't be translated

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/pybee.github.io#244]
The language menu should be more like the one in Wikipedia, where no matter which language is the page you're visiting, the links for other languages are written in those languages.

As it is right now, there is a bit of an accessibility problem: if someone happens to follow a [link to, say, the German version](https://pybee.org/de_DE/), they have to either know what "Sprachen" means or know the structure of the website to access their language.

We should probably consider making the "Languages" item of the menu untranslated as well, as the probability of random people knowing what "Languages" mean is likely higher for English than for other languages.

Any thoughts?

**Comment by goanpeca** [comment]
I agree! lets change those :-p

**Comment by eliasdorneles** [comment]
I'd go with both "Languages" plus an icon
