### ISSUE TITLE
Use better formatted issue pages

### ISSUE THREAD

**Issue by SanketDG** [pybee/pybee.github.io#247]
Use the following issue links in https://pybee.org/contributing/how/

https://github.com/issues?q=user%3Apybee+label%3Aup-for-grabs+is%3Aopen&type=Issues
https://github.com/issues?q=user%3Apybee+label%3Afirst-timers-only+is%3Aopen&type=Issues

**Comment by goanpeca** [comment]
@SanketDG thanks for the suggestion. I would encourage you to submit the pull request. It is very easy, you can update the page https://pybee.org/contributing/how/ by clicking on the `Edito on Github` Button at the top right.

<img width="1410" alt="screen shot 2017-11-10 at 12 11 07" src="https://user-images.githubusercontent.com/3627835/32669967-46b51390-c610-11e7-96a4-1d509148e26a.png">


Cheers
