### ISSUE TITLE
pybee.org homepage console error

### ISSUE THREAD

**Issue by adrienbrunet** [pybee/pybee.github.io#33]
I noticed the following error in my console on your homepage:
Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)

Don't know if you can fix it or if it's on hubspot side.
If this is irrelevant, feel free to close it. It's like a -9999 priority issue.

Cheers! :beer: or shoud I say :bee:r!

**Comment by freakboy3742** [comment]
Thanks for the report. I've noticed that in my logs before - but as you say; priority -9999 issue, so I didn't get around to formally reporting it. However, it's almost certainly a trivial fix - something to do with a Bootstrap dependency being missing. Not sure what it is, but it's an easy place for someone to investigate and contribute.
