### ISSUE TITLE
Broken Link in 'Challenge Coins' page.

### ISSUE THREAD

**Issue by mkartic** [pybee/pybee.github.io#330]
The link to MaxCDN blog page seems to have moved. Can this be replaced with a Wayback machine link?

Broken link: https://www.maxcdn.com/blog/beeware-be-sticky/ 
Archive Link: https://web.archive.org/web/20170923205703/https://www.maxcdn.com/blog/beeware-be-sticky/

**Comment by danyeaw** [comment]
I think this would be fine to update the link the internet archive one. Does someone want to submit a PR?

**Comment by SashwatAnagolum** [comment]
Hey @danyeaw, I PRed a couple minutes ago, and have fixed the link. A screenshot of my testing environment is attached with the PR.

**Comment by danyeaw** [comment]
Closed by #332.
