### ISSUE TITLE
Project images 404s

### ISSUE THREAD

**Issue by carltongibson** [pybee/pybee.github.io#43]
Hi. 

The homepage has a few 404s: 

![screenshot 2016-09-23 10 57 54](https://cloud.githubusercontent.com/assets/64686/18780192/9f3f4a3c-817c-11e6-9ed9-226490a0f1aa.png)

The files exist in the project, e.g. https://github.com/pybee/pybee.github.io/blob/lektor/content/project/projects/libraries/toga/toga.png exists.

Also the URLs work without the `-32` suffix, e.g. http://pybee.org/project/projects/libraries/toga/toga.png is fine. 

So, either: 

1. Remove the `-32` suffixes, or
2. Maybe there's a build step to create those images missing

???

Happy to do a PR, certainly for option 1. (Although 2 as well if you can guide me slightly.)

**Comment by glasnt** [comment]
Whoops, sorry @carltongibson, my bad. I'll fix this up. This was based on #42 and me seeing cached images

**Comment by glasnt** [comment]
This has been fixed in 7260d4f, which should roll out to the site soonly. If this fixes what you're seeing, let me know and this issue can be closed.

**Comment by carltongibson** [comment]
Awesome! Side bar images are now showing. Good one.
