### ISSUE TITLE
Video of "Python All the Things" isn't loading because of same origin policy

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/pybee.github.io#54]
Right now if you google `python all the things`, one of the first relevant results is this page:

http://pybee.org/community/resources/python-all-the-things/

Unfortunately, the video isn't loading (tested on Chrome and FF), apparently because of Same Origin Policy:

![pythonallthethings beeware-googlechrome_2016-10-26_01 56 46](https://cloud.githubusercontent.com/assets/37565/19712792/7fa8c72c-9b1f-11e6-9d62-9b78171b5a7e.jpg)

**Comment by glasnt** [comment]
Eek! I'll get this fixed up

**Comment by eliasdorneles** [comment]
Hey, thanks for the prompt response :)

**Comment by glasnt** [comment]
All done! ✨
