### ISSUE TITLE
Somehow, registering for the enthusiasts' newsletter didn't work through the website

### ISSUE THREAD

**Issue by matthiask** [pybee/pybee.github.io#67]
Going directly to pybee.us13.list-manage.com/subscribe/post?u=80484e69d1f766a4f4477b680&id=fe4d05bfd7 fixed it (for me).

I haven't see a captcha on pybee.org, but got one on the URL above. Maybe that's part of the problem.

The error said something about too many retries for my email address, and trying again in 5 minutes. That didn't help.

**Comment by goanpeca** [comment]
@matthiask is this still valid. Can we close this @freakboy3742 ?

**Comment by matthiask** [comment]
Oh, I'm quite sure it isn't. Thanks for the reminder.
