### ISSUE TITLE
Text-wrapping bug

### ISSUE THREAD

**Issue by treyhunner** [pybee/pybee.github.io#8]
When description wraps to multiple lines, the UI breaks.

This is particularly problematic because with different window sizes, the text wraps differently.

I noticed this by attempting to make a long description text for cricket.

![selection_761](https://cloud.githubusercontent.com/assets/285352/15762833/db5ee7b2-28d4-11e6-8b5c-ea93470d2b21.png)

Noted in #7.

**Comment by freakboy3742** [comment]
We're working on a new design; this issue no longer exists.
