### ISSUE TITLE
The copyright notice still says 2016

### ISSUE THREAD

**Issue by alanbato** [pybee/pybee.github.io#83]
I was reading through the first collaboration guide and noticed something wasn't quite _right_.
![screenshot_20170106_030858](https://cloud.githubusercontent.com/assets/11902612/21713068/b1b0c1b2-d3bd-11e6-9519-ec29d15b2e09.png)
I know this isn't that big of a deal, but I just wanted to let you know in case you weren't aware of it :) 

Cheers! :snake: :bee:

**Comment by glasnt** [comment]
Oh the humanity! Thank you for pointing out such an important bug!

If you want to submit a pull request that corrects this, we will merge it in ASAP. 

🐍

**Comment by alanbato** [comment]
Sorry for the delay, here's the PR #84 :snail: :snake:

**Comment by glasnt** [comment]
Thank you! ✨
